<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Für AppConfig / UserSecrets -->
		<UserSecretsId>3cacf937-2653-4612-88b9-2a336b3581b6</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<!-- Configuration -->
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.2" />

		<!-- PostgreSQL -->
		<PackageReference Include="Npgsql" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="MRP.Tests" />
	</ItemGroup>

</Project>